### ISSUE TITLE
Make a wizard for tokenscript

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/TokenScript#102]
- Standard template tokenscripts - 721, 20, 875
- Plug in layout HTML and JS
- Plug in contract address 
- Sign with metamask

**Comment by hboon** [comment]
@James-Sangalli If we want ERC20 support, remember to create an issue to add TokenScript support for in iOS. It hasn't been added earlier primarily because the screen layout for ERC20 is quite different from non-fungibles currently.

Maybe it's the same for Android.

**Comment by hboon** [comment]
> * Plug in contract address

Might be nice if there's a way to automatically deploy a template contract that works with the template TokenScripts by ticking a checkbox? Could be an enhancement.

**Comment by James-Sangalli** [comment]
Started here (private until ready to show): https://github.com/AlphaWallet/TokenScript-Wizard

**Comment by James-Sangalli** [comment]
Handled in onboarding resources

**Comment by hboon** [comment]
@James-Sangalli While onboarding examples/templates help, a wizard is still better. Imagine something like npm/yarn:

```
tks create #Create an example with TokenScript file and contract source
tks build #runs the make file
tks install #install stuff used by make file
tks lint
tks help #URLs etc or just open a particular site
```
