### ISSUE TITLE
schema: change multi origin to origins (should we)?

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/TokenScript#115]
the current syntax:

    <ts:attribute-type id="venue" syntax="1.3.6.1.4.1.1466.115.121.1.15">
      <ts:name xml:lang="en">Venue</ts:name>
      <ts:name xml:lang="zh">场馆</ts:name>
      <ts:name xml:lang="es">Lugar</ts:name>
      <ts:name xml:lang="ru">место встречи</ts:name>
      <ts:origin bitmask="0000000000000000000000000000000000FF0000000000000000000000000000" as="mapping">
        <ts:mapping>
          <ts:option key="1">
            <ts:value xml:lang="ru">Стадион Калининград</ts:value>
            <ts:value xml:lang="en">Craig Wright's House</ts:value>
            <ts:value xml:lang="zh">加里宁格勒体育场</ts:value>
            <ts:value xml:lang="es">Estadio de Kaliningrado</ts:value>
          </ts:option>
        </ts:mapping>
      </ts:origin>
      <ts:origin contract="erc875" as="mapping">
        <ts:function name="isExpired">
          <ts:inputs>
            <ts:uint256 ref="tokenID"/>
          </ts:inputs>
        </ts:function>
        <ts:mapping>
          <ts:option key="1">
            <ts:value xml:lang="ru">Стадион Калининград</ts:value>
            <ts:value xml:lang="en">Craig Wright's House</ts:value>
            <ts:value xml:lang="zh">加里宁格勒体育场</ts:value>
            <ts:value xml:lang="es">Estadio de Kaliningrado</ts:value>
          </ts:option>
        </ts:mapping>
      </ts:origin>
    </ts:attribute-type>

the new syntax:

    <ts:attribute-type id="venue" syntax="1.3.6.1.4.1.1466.115.121.1.15">
      <ts:name xml:lang="en">Venue</ts:name>
      <ts:name xml:lang="zh">场馆</ts:name>
      <ts:name xml:lang="es">Lugar</ts:name>
      <ts:name xml:lang="ru">место встречи</ts:name>
      <ts:origins>
        <ts:token-id bitmask="0000000000000000000000000000000000FF0000000000000000000000000000" as="mapping">
        </ts:token-id>
        <ts:ethereum contract="erc875" as="mapping">
          <ts:function name="isExpired">
            <ts:inputs>
              <ts:uint256 ref="tokenID"/>
            </ts:inputs>
          </ts:function>
        </ts:ethereum>
      </ts:origins>
      <ts:mapping>
         <ts:option key="1">
          <ts:value xml:lang="ru">Стадион Калининград</ts:value>
          <ts:value xml:lang="en">Craig Wright's House</ts:value>
          <ts:value xml:lang="zh">加里宁格勒体育场</ts:value>
          <ts:value xml:lang="es">Estadio de Kaliningrado</ts:value>
        </ts:option>
      </ts:mapping>
    </ts:attribute-type>

Rationale 𝑓𝑜𝑟 such a change:

1. It seems to be reasonable for mapping to be per-attribute-type instead of per-origin. Each origin can, however, specify whether or not to use the mapping. Should the need to use more than 1 mappings for an attribute rises, the mapping can be given an id and referenced separately.

2. We haven't defined the syntax for attestation origin or dependency origin (one token depends on another token, and its attribute is sourced from that token). The complexity of them might demand its own element tag. Use one element tag for one origin to start in a clear way.

Rational 𝑎𝑔𝑎𝑖𝑛𝑠𝑡 such change:

Couldn't think of any yet.

Consider this together with #114

**Comment by hboon** [comment]
The new syntax with `<origins>` sounds much better.

A. Have you considered how children in`<origins>` are to be processed? Are they ordered by precedence or is it going to be more sophisticated? `<origins>` makes it easier to expand beyond precedence by ordering similar to rationale (2).

B. Stronger "typing". There's less room for error in parsing the XML as we make changes to the schema.

C. I feel like semantically `<mapping>` should still be part of each `<origins>` child as they are implementation details of each origin, i.e:

```
<ts:origins>
  <ts:token-id>
    <ts:mapping/>
  </ts:token-id>

  <ts:ethereum contract>
    <ts:mapping/>
  </ts:ethereum contract>
</ts:origins>
```

But this will force developers to duplicate mappings and introduce more room for error. So leaving them as direct children of `<attribute-type>` is still better.

**Comment by colourful-land** [comment]
> A. Have you considered how children in`<origins>` are to be processed? Are they ordered by precedence or is it going to be more sophisticated? `<origins>` makes it easier to expand beyond precedence by ordering similar to rationale (2).

Thanks. Naïvely, I think that by now it should be ordered by precedence. But it will grow in complexity.
