### ISSUE TITLE
mapping for numeric string

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/TokenScript#116]
Transfer of 1 DA is actually

    tokenContract.transfer(0x2222222222222222222222222222222222222222, 1000000000000000000)

Some kind of mapping is needed to map user entry data with the attribute value. I hesitate a bit to reuse `<mapping>` tag with a varied syntax as it is unclear if the mapping maps user entry to attribute, or attribute to the user entry.

Question: when you see this empty mapping:

        <ts:action>
            <ts:attribute-type id="amount" syntax="">
                <ts:name xml:lang="en">Amount in DAI</ts:name>
                <ts:name xml:lang="zh">代幣金額</ts:name>
                <ts:origin entry="user">
                    <mapping>[some magic happens here]</mapping>
                </ts:origin>
            </ts:attribute-type>
            <ts:name xml:lang="en">Transfer to xDAI</ts:name>
            <ts:view/>
        </ts:action>

do you feel

1. the mapping rule maps user's input, say 1DAI, to attribute value, say 1000000000000000000
2. the mapping rule maps the attribute value 1000000000000000000 to user's input 1DAI.

P.S. To provide context, the security model is that as long as the user typed in a value and the value is pristine (Javascript hasn't updated it), when it is used to assemble a transaction, the value is used as is without any warning or highlight. Therefore it's needed to define the attribute in TokenScript and the name of the attribute is used in final confirmation (in the action sheet)

Calling @hboon @James-Sangalli @JamesSmartCell I think intuitively your answer is
d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f90da3a666eec13ab35

(to verify, type your answer and get its sha256, for example, if your answer is 1, type:

    $ echo -n 1 | sha256sum

**Comment by hboon** [comment]
6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b

because this suggest "mapping-from":

```
<ts:origin entry="user">
    <mapping>[some magic happens here]</mapping>
```

**Comment by colourful-land** [comment]
> 6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b
> 
> because this suggest "mapping-from":
> 
> ```
> <ts:origin entry="user">
>     <mapping>[some magic happens here]</mapping>
> ```

I learned that intuition must rule over consistency. Copied from my notebook:

> [after some work in a git repo] a developer hit “checkout” on a directory. The graphical user interface started to download a changeset; as the progress rears, it asked the user if he intends to discard the changes, as there are too many of them. What “the changes” mean here? Does it mean if the user wants to discard the changes introduced (downloaded) by hitting “checkout” button, or does it mean that all the changes user did to the software before using “checkout”? What is “too many”, is it that the changes brought forward by “checkout” too many for the computer to handle, and the computer *wants* to discard them, or is it that the user has too many changes to be affected by “checkout” and the computer was kind in preventing the user to lose his work? It seems natural, given this specific context, for a developer to believe it meant the former, however, the manual stated that it is always the latter case: “checkout” acts like a reset button causing all local changes to be discarded. The word “checkout” is spoken from the computer’s perspective, to check out a clean state overwriting the existing one made dirty by users change; not from a user’s perspective, to check out what computer has to offer. This is made even worse by the common use of "check out", which means finalising a serial of decisions (shopping in a supermarket), and not nearly resemble the intended effect (discard a serial of decisions) here.

Problem being, once I work on it for a while, I forget what it is like when I was introduced to the context.
