### ISSUE TITLE
link http://tokenscript.org/2019/04/tokenscript broken

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/TokenScript#117]
I find the link from:
https://github.com/AlphaWallet/TokenScript/blob/master/examples/ticket/AdmissionTicket.xml

<ts:token xmlns:ts="http://tokenscript.org/2019/04/tokenscript"

<img width="685" alt="Screen Shot 2019-04-23 at 5 35 26 pm" src="https://user-images.githubusercontent.com/33795543/56570820-3b1eb200-65ee-11e9-8d72-74d82ba178b7.png">

**Comment by colourful-land** [comment]
xmlns is not a link - it doesn't need to be "accessed". github rendered it as a link because it wants to. as per xml standards, it's not required to serve anything at the xmlns

We probably should still put something there anyway, for those people believe it's a link.

**Comment by colourful-land** [comment]
@bootingman the best way to do that is perhaps to redirect this "link" to a post in tokenscript.org

**Comment by colourful-land** [comment]
Change of mind - it seems man adopted the solution of putting the schema file at the said location. We would do the same, but only for schema 2019/05 otherwise it's too much work

**Comment by colourful-land** [comment]
I'll adopt a framework for links like this to work in 2019/04 as well. Pul request coming in days.
