### ISSUE TITLE
http://tokenscript.org broken

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/TokenScript#118]
<img width="1372" alt="Screenshot 2019-04-24 at 12 10 41 PM" src="https://user-images.githubusercontent.com/56189/56631922-fcd6d080-6689-11e9-97fa-d053183d8041.png">

**Comment by hboon** [comment]
Maybe related. http://www.tokenscript.org doesn't redirect to https://www.tokenscript.org anymore (not sure if it ever did), but Safari and Chrome complains that URLs aren't secure when it isn't https.

**Comment by bootingman** [comment]
Now, all of them are available
- http://www.tokenscript.org/
- https://www.tokenscript.org/
- http://tokenscript.org/
- https://tokenscript.org/

**Comment by hboon** [comment]
@bootingman Shouldn't http://www.tokenscript.org/ redirect to https://www.tokenscript.org/ too?

**Comment by colourful-land** [comment]
> @bootingman Shouldn't http://www.tokenscript.org/ redirect to https://www.tokenscript.org/ too?

I think it should redirect to https://tokenscript.org. Between 2004 and 2014, the trend has changed to the complete elimination of www header. I think the change of www.w3.org to w3.org is the final nail to the coffin. In fact, https://www.tokenscript.org does not need to work, only http://www.tokenscript.org need to.

But we can sort that out as we build a static web-page based website for tokenscript.org

I'll close this and I welcome reopening if you see fit.

**Comment by colourful-land** [comment]
@boon you might wonder why @bootingman set http://www.tokenscript.org to redirect to http://tokenscript.org and not https://tokenscript.org.

I think he has Chinese user in mind. In China, SSL websites were randomly throttled (at about 1-byte-per-second so it doesn't time out as experiments showed frustration dissuade usersb etter than an error)
