### ISSUE TITLE
origins tag has 2 different semantics at token and in (action/)attribute-type

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/TokenScript#130]
Referring (A) to:

```
    <ts:origins>
        <ts:ethereum contract="dai">
        </ts:ethereum>
    </ts:origins>
```

and (B): 

```
<ts:action>
...
                <ts:origins>
                    <!-- e18 is a hard coded multiplier.
                    rationale for hardcoding: avoiding over-design  -->
                    <ts:user-entry as="e18"/>
                </ts:origins>
</ts:action>
```

Looks like the schema allows (A) to include <user-entry> too, syntax-wise. Is that going to be a problem? Similar for `<ethereum>/<inputs>`. Should they be different tags?

**Comment by hboon** [comment]
@colourful-land Also the "address" tag in 2 places.

**Comment by colourful-land** [comment]
This will be addressed as part of the PR to allow tokenscript with <action> as root element.

**Comment by colourful-land** [comment]
> @colourful-land Also the "address" tag in 2 places.

I found that That is addressed in the master.
