### ISSUE TITLE
Remove byte, bytes, bytesN from schema for version 2019/05

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/TokenScript#148]
Let's drop them first.

bytesN: `bytes32` are arrays [^1]. If we support `bytes32`, then we can support `bytes1`-`bytes32` as well as `byte` (which is `bytes1`).

`bytes` and `X`[] (where `X` can be `byte`, `bytes`, `bytesN` and other types) are different from the above.

[^1]: Perhaps `bytesN` are a byte sequence is a more accurate terminology.

**Comment by James-Sangalli** [comment]
@hboon @colourful-land need the bytes var for the CDP.

**Comment by colourful-land** [comment]
@hboon I understand that schema should not support features that code doesn't support. Can we support `<bytes>` for @James-Sangalli ? It would look similar to `<address>`.

**Comment by hboon** [comment]
@colourful-land let's hold it for a while. @James-Sangalli can assume that <bytes> would be available for the moment, but can't test it. We can update the schema (maybe still make it 2019/05 then) and implement it in the TokenScript clients once we have everything working with the DAI-bridge example? It might just be a simple change in the clients (or not). But either way, we should finished up supporting DAI-bridge first. There's still quite a few moving parts to resolve and implement.

Follow up at #154.
