### ISSUE TITLE
add <view> content for xdai bridge

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/TokenScript#176]

**Comment by James-Sangalli** [comment]
Spoke with @JamesSmartCell, mutually decided to use the native send screen as this would be the most natural approach. If this is successful, I will close the issue and if not, will make a makeshift screen emulating the send screen.

**Comment by colourful-land** [comment]
@hboon needs to be cross with this. If you choose that on Android, depends on how easy it is for a similar configuration to be built for iOS, there is a small chance boon may find it easier to generate the needed HTML or that `<view>` must be back.

**Comment by James-Sangalli** [comment]
@hboon @JamesSmartCell @colourful-land actually we decided to go back to the view way, its more natural even though we cannot yet see the balances.
