### ISSUE TITLE
proposals for tutorial 

### ISSUE THREAD

**Issue by bobjiang** [AlphaWallet/TokenScript#214]
This is a proposal for current tutorial.
From the discussion with Boon, I realize that there are 2 scenarios in current tutorial:

1. a quick go through with designed smart contract and token script
2. the second scenarios is for a developer would like to go deeper, let's say, customize the token script, 

So we could divide the tutorial into 2 tutorials:

1. Quick go through token script in 5 minutes
2. Design your token script in 10 minutes

**Comment by bobjiang** [comment]
1 more suggestion, for tutorial 1 (quick go through), provide repo server (host by you) to see the demo result. (I didn't find the repo info in tutorial, but saw it in Beijing hackathon). Not sure if it makes sense to expose the repo server.

**Comment by hboon** [comment]
@bobjiang thanks for taking the time to do this.

**Comment by James-Sangalli** [comment]
> 1 more suggestion, for tutorial 1 (quick go through), provide repo server (host by you) to see the demo result. (I didn't find the repo info in tutorial, but saw it in Beijing hackathon). Not sure if it makes sense to expose the repo server.

Already handled, the EntryToken.tsml example is hosted by the server

**Comment by James-Sangalli** [comment]
> This is a proposal for current tutorial.
> From the discussion with Boon, I realize that there are 2 scenarios in current tutorial:
> 
> 1. a quick go through with designed smart contract and token script
> 2. the second scenarios is for a developer would like to go deeper, let's say, customize the token script,
> 
> So we could divide the tutorial into 2 tutorials:
> 
> 1. Quick go through token script in 5 minutes
> 2. Design your token script in 10 minutes

Thanks for this, what were they hoping for in particular? Was the motivation to be able to get going or to understand it? Was there something they thought was lacking in particular?

**Comment by jzaki** [comment]
@bobjiang Does this help? -> [Developing your first Tokenscript](https://community.tokenscript.org/t/overview-for-developing-your-first-tokenscript/269)
