### ISSUE TITLE
specify return-type along "as"

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/TokenScript#225]
As discussed in the email regarding bytes and bytesN

Quote Boon:

A) bytes "123456" is encoded as 0x313233343536
B) bytes "12" is encoded as 0x3132
C) bytes1 0x12 is encoded as 0x1200...0 (padded to 32 bytes)
D) bytes2 0x1234 is encoded as 0x123400...0 (trailing 0s so it's padded to 32 bytes)
E) bytes2 0x1200 is encoded as 0x120000...0 (trailing 0s so it's padded to 32 bytes)
F) bytes2 0x0012 is encoded as 0x001200...0 (trailing 0s so it's padded to 32 bytes)

we need to add a return type attribute to function calls so that we do not confuse the apps when interpreting such variables. 

Since we are adding this, we can get replace the "as" attribute with return-type and then cast with that.

Since July schema added in bytes, we ought to add this and then skip July in lieu of a later month.

**Comment by colourful-land** [comment]
Thanks. Letting @hboon know that we are tracking this.

**Comment by colourful-land** [comment]
Implicit conversion

- if the attribute type is an Integer, and the origin is returned with `as="utf8"`, then there is an implicit conversion whose rules are not defined anywhere in the TokenScript file.
- Similarly, if the original is returned with `as="bytes"`, how that is converted to an Integer is implicitly big-endian, but what if the smart contract author intended to use *two's complement*?

**Comment by hboon** [comment]
We might have cases like this that has a defacto conversion path (can't think of any at the moment. Brain is slow) already.

But the examples for implicit conversion above aren't so clear-cut, so we can either decide and on how to convert for each case, preferably with a rule or two to govern the decision for consistency, or we can label it as undefined behavior and shove it under the carpet..

**Comment by James-Sangalli** [comment]
Solved with 2019/10
