### ISSUE TITLE
Need to understand the abstraction logic between tokenization standards (ERCs?) and TBML components

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/TokenScript#24]
Mr. Guo Yong spent more than 15 years working in tech companies in Silicon Valley and top global financial institutions. He served as a consultant and executive at global companies such as KPMG, World Bank, Apple, and LinkedIn. He founded two big data companies in Silicon Valley and successfully exited. Mr. Guo graduated from Carnegie Mellon University majoring in electrical computer engineering and is the Conrad scholarship recipient of the department.
[TBML-feedback.notes.txt](https://github.com/AlphaWallet/TBML/files/2922132/TBML-feedback.notes.txt)

He said:

>> 2.1.1 Need to understand the abstraction logic between tokenization standards (ERCs?) and TBML components.
>> ----------------------------------------------------------------------------------------------------------

    I think the logic behind the abstraction is core for someone to
    understand the rationale and use case of TBML. Some argument/examples
    on the mapping between TBML and some tokenization standards would be
    vastly helpful.

**Comment by colourful-land** [comment]
The feedback has to be broken down to many issues since a lump sum issue can't be marked closed unless every sub-issue is. Therefore, I changed the title to address the first issue he raised. 

e.g. "We need to persistently improve our product" can't be an issue because that issue can never close.

**Comment by colourful-land** [comment]
From @zhangzhongnan928 :+1: 

> Rego, services, warranty need to be owned by car token 😊.

"Depend" on the car token. Rego may further depend on the user's identity (an attestation, which is also a from of a token)

> TBML is another layer on top of ERCs(smart contract). Shouldn't put all the information/logic in smart contract for cost, security and privacy reasons. And shouldn't keep them all in the DApp(DApp website), for integration and many other reasons. TBML file is a signed XML file associated with the token.

Yes that's right.

**Comment by zhangzhongnan928** [comment]
”Token code” is a new word, but quite easy to understand.
Token Code is written in smart contract and TBML file.


TBML is another layer on top of ERCs(smart contract). Shouldn't put all the information/logic in smart contract for cost, security and privacy reasons. And shouldn't keep them all in the DApp(DApp website), for integration and Security reasons, since the user should not trust dapp code, but they can trust token code. Token Code is written in smart contract and TBML file. TBML file is a signed XML file associated with the token.


		
Victor Zhang
CEO, AlphaWallet
							
Not only display information, @Alpha_Wallet let you preform the functions: DEPOSIT, WITHDRAW, PAYBACK, GENERATE, MO… https://t.co/6dJfdvnM3i

**Comment by colourful-land** [comment]
Please post your questions to https://www.tokenscript.org/c/ethereum and I'll follow up from there.
