### ISSUE TITLE
Discovery token in Chinese AlphaWallet

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/TokenScript#246]
![70E0D055-ACC2-4545-9A6C-49C85534AD0E](https://user-images.githubusercontent.com/33795543/65677338-c6680c00-e094-11e9-8eca-26e92d36ac6e.jpeg)
![7C6D1DCE-22C3-4C52-8F30-9E2819CC8DE4](https://user-images.githubusercontent.com/33795543/65677340-c6680c00-e094-11e9-9362-1d448f26f63c.png)

**Comment by hboon** [comment]
Issue is in iOS TokenScript client
