### ISSUE TITLE
Add pDai, pUSDT and pETH and USDx into discovery token

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/TokenScript#249]
pDai  180 USD
0x6f9D718CaF76055E697AdfFD5E9f9f94753a7501
pETH 160 USD
0x26F5f49E3bb3626b53E4573F07F8587F010019B5
pUSDT 160 USD
0x7a6aAB486A2Bed37c7Cd523Eb60B3A42533f8906
One button> landing page > go to this portal https://margin.ddex.io/funding

USDx 180USD
0xeb269732ab75A6fD61Ea60b06fE994cD32a83549
Two buttons
One button> landing page > go to this portal https://usdx.dforce.network
One button> landing page > go to this portal https://www.lendf.me/supply

1. Add these token
2. Write a simple TS for each token
Possible to add an action card which just open
https://margin.ddex.io/funding in Dapp Browser
3. Make sure these token can show up automatically on both Android and iOS

![8980E5C2-5544-4B3A-9E50-717C6F545463](https://user-images.githubusercontent.com/33795543/65833516-8f079280-e314-11e9-908d-63e3be39df65.jpeg)

https://margin.ddex.io/funding
![3C1F1D5E-7D98-496A-8392-EF8D3E275A7D](https://user-images.githubusercontent.com/33795543/65833520-a47cbc80-e314-11e9-81ee-6509c871b93b.png)

**Comment by James-Sangalli** [comment]
@zhangzhongnan928 

None of these are possible with the current state of TokenScript as each require you call the batch function which takes a special array of a custom struct object.

It will be some time till we have implemented a way to do this in TokenScript as we have neither arrays nor the ability to form struct objects yet.

**Comment by James-Sangalli** [comment]
@zhangzhongnan928 the one action we can do is to deposit into your trading account but this only would work for ether because it can be invoked by sending ether directly to the contract. Not very useful for users however.

**Comment by zhangzhongnan928** [comment]
> @zhangzhongnan928
> 
> None of these are possible with the current state of TokenScript as each require you call the batch function which takes a special array of a custom struct object.
> 
> It will be some time till we have implemented a way to do this in TokenScript as we have neither arrays nor the ability to form struct objects yet.

Don't need any actions besides opening up their own portal in AlphaWallet DApp Browser

**Comment by zhangzhongnan928** [comment]
1. Add these token in discover pool, DDEX will send those tokens to discovery address
2. Write a simple TS for each token, **Don't need any actions besides opening up their own portal in AlphaWallet DApp Browser**
3. Make sure these token can show up automatically on both Android and iOS

**Comment by zhangzhongnan928** [comment]
Adding USDx
0xeb269732ab75A6fD61Ea60b06fE994cD32a83549
Two buttons
One button> landing page > go to this portal https://usdx.dforce.network
One button> landing page > go to this portal https://www.lendf.me/supply
