### ISSUE TITLE
Should be allowed to set user-entry attributes via props

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/TokenScript#256]
Currently if I want to do something with the user-entry before it goes to the TokenScript I need to hack it to fill an empty HTML element which sets the attribute. 

Should be able to do so with a simple this.props.userEntry = blah

**Comment by hboon** [comment]
@James-Sangalli is this so the user can (optionally) input a value, the TokenScript can do some processing (or acquire an input via an API call) and then the TokenScript client can use that result as the userEntry attribute value?

**Comment by James-Sangalli** [comment]
Event support will make this redundant
