### ISSUE TITLE
Illustrate the concept that the user know what token they can get before purchase, 𝑛𝑜𝑡 𝑎𝑓𝑡𝑒𝑟

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/TokenScript#26]
Is there a way for the user to know what token they will get before the transaction and not after? If you read through the paper (a lot of work to read, I know), you will notice that the cards (generated by the dapp browser) enjoy a different level of trust than the dapp below it. The user wants to know what tokens they can get because if a warranty is just promised, not given in the form of a token, the buyer might choose not to check out at all. In other words, a buyer must know both the input and output to make a decision. Imagine if you want to resell the product later, it will not fetch a good market value because it can only be resold with ebay which has a higher cost of the transaction due to the extra need to prove the availability of warranty.

Regarding "a buyer must know both the input and output to make a decision" you can see it the other way as "a buyer will only know the deliverable before he proceeds with payment since once payment is done, it is done. Atomicity is the key of the blockchain transactions, either the transaction is successful, and you get ALL THE TOKENS that represents your purchase, or your payment will be returned. This is DIFFERENT from traditional business, where Payment is made first, then, you may or may not get your deliverable, and if you don't get it, you can do a chargeback. You can't do a chargeback in blockchain without introducing huge infrastructure, so you need to see what tokens you can get. That's just how blockchain works.

**Comment by colourful-land** [comment]
Any update @farrahfazirah ?

**Comment by farrahfazirah** [comment]
Purchase without shipment token
![purchase-without-shipment-token](https://user-images.githubusercontent.com/20555752/54707446-13b27080-4b7c-11e9-82fb-7c19da57071f.jpg)


Purchase with shipment token
![purchase-with-shipment-token](https://user-images.githubusercontent.com/20555752/54707456-1ad97e80-4b7c-11e9-87b7-1ffcfa251cdf.jpg)

**Comment by colourful-land** [comment]
This is a complicated concept very beautifully down! I know I can trust you to pull this off!

Can you

1. Make the expiry less alarming?
2. In your branch, save the two images in doc/img
3. Delete the two files doc/purchase-without-shipment-token.jpg and doc/purchase-with-shipment-token.jpg
4. Pull-request the result.

Thanks!

**Comment by hboon** [comment]
I'd like to add that they remind me of Apple and Stripe. Both companies known for great design!

**Comment by farrahfazirah** [comment]
I've done the necessary steps and changed the icon to a less alarming one. The change can be seen on the pull request here: https://github.com/AlphaWallet/TokenScript/pull/65
