### ISSUE TITLE
404 on https://github.com/AlphaWallet/TokenScript/tree/master/examples/nft

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/TokenScript#261]
https://github.com/AlphaWallet/TokenScript/tree/master/examples/nft

<img width="1016" alt="Screen Shot 2019-10-30 at 11 56 19 am" src="https://user-images.githubusercontent.com/33795543/67820189-5d007080-fb0c-11e9-841c-0d04100385c7.png">

**Comment by James-Sangalli** [comment]
https://github.com/AlphaWallet/TokenScript/commit/1ca0325c93213c4e30ebf276f5966ad456a7d5a9
