### ISSUE TITLE
Move the Karma Car token to examples

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/TokenScript#262]
And update it to new schema

**Comment by James-Sangalli** [comment]
@JamesSmartCell bump, you can give the file to me and I can upload it if you want

**Comment by zhangzhongnan928** [comment]
> @JamesSmartCell bump, you can give the file to me and I can upload it if you want

I think it is here, but I don't think it is under the new schema 
https://github.com/JamesSmartCell/Karma-Car-Owner-Token

**Comment by James-Sangalli** [comment]
@JamesSmartCell I made a signed version here: https://github.com/AlphaWallet/TokenScript-Repo/blob/add-karma/aw.app/2019/10/karma.tsml

But you need to publish the un-canonicalized version here as your repo doesn't have it
