### ISSUE TITLE
weth, unwrap, wrong text

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/TokenScript#266]
![8D0A5C2F-9B99-4D97-B249-43CBE93A1047](https://user-images.githubusercontent.com/33795543/68386227-b5400e00-01af-11ea-94d2-c6196c7dc36e.jpeg)

**Comment by James-Sangalli** [comment]
https://github.com/AlphaWallet/TokenScript/commit/38295af4eaa823501e66ae3afbb30d77374d1747
