### ISSUE TITLE
xdai bridge 

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/TokenScript#267]
![149457E6-5B63-4D3C-9FE6-EAB07484F52A](https://user-images.githubusercontent.com/33795543/68387608-ce968980-01b2-11ea-96f3-8ca5c9aeb8d0.png)

Shows failed, but actually succeed

**Comment by James-Sangalli** [comment]
@zhangzhongnan928 can't reproduce this on my device, also I think this would be an iOS issue

**Comment by James-Sangalli** [comment]
No longer an issue
