### ISSUE TITLE
Write new layout for UEFA tickets in SHTML (JS, HTML, CSS)

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/TokenScript#274]
To be done with: https://github.com/AlphaWallet/TokenScript/blob/UEFA/examples/UEFA/UEFA.en.shtml

@developerpeachy branch of UEFA and add the layout there

Design: https://app.zeplin.io/project/5dccab308fad0116efb4e2af/screen/5dccb73b242c1216bccdb7f7

**Comment by developerpeachy** [comment]
Hi James, 

Can you send me a proper invite to the Zeplin project? thanks

**Comment by tomekalphawallet** [comment]
Check now.

Tomek

**Comment by developerpeachy** [comment]
Should be done here: https://github.com/AlphaWallet/TokenScript/pull/283

**Comment by developerpeachy** [comment]
@zhangzhongnan928 suggested to change the name of the ticket from "UEFA EURO 2020 TICKET" to "UEFA EURO 2020 HOSPITALITY TICKET" so if this is ok i'll adjust the text.

**Comment by zhangzhongnan928** [comment]
Just the “ UEFA EURO 2020 HOSPITALITY” is fine

**Comment by James-Sangalli** [comment]
https://github.com/AlphaWallet/TokenScript/pull/283
