### ISSUE TITLE
Cdai TokenScript withdraw doesn’t work as expected 

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/TokenScript#278]
https://etherscan.io/tx/0x59fd668cb84edcaa62b8d6ee2e27783ade5038cc2079e86de41b38cbe421b535

Transection successful, but didn’t convert any cdai back to Dai. 

Build 2.17(313)

**Comment by James-Sangalli** [comment]
@zhangzhongnan928 tx says you tried to withdraw: 765407000000 but your balance is only: 4762481687

Could be an issue with the multiplier, let me check

**Comment by James-Sangalli** [comment]
@zhangzhongnan928 can't reproduce on my side, I typed in 40 to redeem and it did that.

**Comment by zhangzhongnan928** [comment]
> @zhangzhongnan928 tx says you tried to withdraw: 765407000000 but your balance is only: 4762481687
> 
> Could be an issue with the multiplier, let me check

It is because of the disappeared transactions come back again.

**Comment by James-Sangalli** [comment]
> > @zhangzhongnan928 tx says you tried to withdraw: 765407000000 but your balance is only: 4762481687
> > Could be an issue with the multiplier, let me check
> 
> It is because of the disappeared transactions come back again.
> 
> but why it shows success

@zhangzhongnan928 success only means the transaction executed successfully, it could have failed to run the code it wanted but still succeed as a transaction
