### ISSUE TITLE
Need to set a default value for UEFA example's redemption state before the function call returns

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/TokenScript#280]
If the function is slow or fails to return, it looks like it is "redeemed", but is actually unknown

Here: 

https://github.com/AlphaWallet/TokenScript/commit/7b16a1bd662817a1b0676763b8ac47f80f8a4bc2#diff-c0f2b3032bfdab77634a81aa7362051fR110-R113

**Comment by James-Sangalli** [comment]
Solved here: https://github.com/AlphaWallet/TokenScript/commit/3c217f1981583b2baa2f177f3ee7a0336a3c7b96

Interestingly, it is not a load problem at all, I was using the conditional wrong. See: https://stackoverflow.com/questions/23061921/javascript-ifx-vs-ifx-true

**Comment by James-Sangalli** [comment]
Might still be an issue since RPC could lag or be unavailable

**Comment by James-Sangalli** [comment]
c7e7d3f27c90ffbba707f875ea0646581519401a

Only sets the value if it is loaded, otherwise don't show it.
