### ISSUE TITLE
Deploy new 721 compatible contract on Rinkeby and xDAI

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/TokenScript#281]
- [x] Testing OpenSea
- [x] if works, may consider include a simple piece of metadata for Opensea and other wallets.

**Comment by James-Sangalli** [comment]
@zhangzhongnan928 

Rinkeby: https://rinkeby.etherscan.io/address/0xc1c14278cc455d9dfa0b0257af40862bd8677efc
xDAI: https://blockscout.com/poa/xdai/address/0x0f43923667843bccafd12a5c001a7838fa5fc8ab/transactions

**Comment by zhangzhongnan928** [comment]
Contrat can be picked up on opensea 

- [ ] Will test token later
