### ISSUE TITLE
Get edcon details

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/TokenScript#282]
- What information is to be encoded into the ticket?
- What network? 
- How many tickets?

**Comment by zhangzhongnan928** [comment]
•the EDCON theme and 5 Type of ticket, plus basic info like venue, location city time dat and etc.
•xDai or Ethereum
• no more than 3000


app name: unicon，
Color: same as unitimes https://apps.apple.com/au/app/unitimes/id1435091625
logo: similar to unitimes，
Ticket cat: 5（ABCDE）
Ticket design: follow EDCON.io
