### ISSUE TITLE
Translate UEFA to Chinese 

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/TokenScript#289]
Need to do the following:

- Go through the XML file https://github.com/AlphaWallet/TokenScript/blob/master/examples/UEFA/UEFA.xml and add the "zh" section wherever there is an "en" section.
- Copy the en.shtml layout file and create zh.shtml; in there you need to translate all the english text into chinese.

**Comment by zhangzhongnan928** [comment]
@James-Sangalli can put in one example, then I can follow

**Comment by James-Sangalli** [comment]
https://github.com/AlphaWallet/TokenScript/blob/master/examples/fifa/fifa.xml

but you need to copy the layout file and make a new one with .zh.shtml

@colourful-land maybe you want to pick this up instead?
