### ISSUE TITLE
re-organize the files and dirs

### ISSUE THREAD

**Issue by bobjiang** [AlphaWallet/TokenScript#30]
e.g for the docs dir, there are also assests like images (jpeg, png etc).

Please mkdir an assets or images dir in the root dir of repo, and move them to that dir.

Thanks a lot :)

**Comment by colourful-land** [comment]
The remaining 2 images will be cleared out when @farrahfazirah is back to work. she is in holiday

**Comment by colourful-land** [comment]
Closing because as #26 closes there will be no remaining images.
