### ISSUE TITLE
FIFA Ticket layout broken

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/TokenScript#304]
![IMG_19DBE2764035-1](https://user-images.githubusercontent.com/33795543/71133256-15fe4400-224e-11ea-813c-6dac5b368329.jpeg)

the layout and the "issuer: Shong Wang" are wrong

**Comment by developerpeachy** [comment]
Moved this to iOS as this FIFA file is outdated. https://github.com/AlphaWallet/alpha-wallet-ios/issues/1624
