### ISSUE TITLE
Remove EURO 2020 logo from UEFA

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/TokenScript#314]

**Comment by hboon** [comment]
@James-Sangalli and based on the design, maybe an appropriate icon to replace the one in the Tickets tab (previously the EURO 2020 logo) if time permits. We removed it in the PR yesterday, but since the entire app is pulled, we can add an icon again.

**Comment by zhangzhongnan928** [comment]
![EURO2020_Composite_Logo_SK-v2-390px-3](https://user-images.githubusercontent.com/33795543/71775859-bd63d080-2fdb-11ea-8756-c4a300013c2c.png)

**Comment by zhangzhongnan928** [comment]
![73bfc78a17994c0dd9db7be8870fe058](https://user-images.githubusercontent.com/33795543/71775866-d2d8fa80-2fdb-11ea-9976-4f293ae859a2.jpg)

**Comment by zhangzhongnan928** [comment]
![73bfc78a17994c0dd9db7be8870fe058 copy](https://user-images.githubusercontent.com/33795543/71787440-dfa52f00-306b-11ea-8b91-b8bc9620b973.jpg)

@tomekalphawallet something like this is fine.

**Comment by zhangzhongnan928** [comment]
@tomekalphawallet need a modified design for UEFA ticket.

**Comment by tomekalphawallet** [comment]
is there anything I can remove from the new logo? We have 2 logos + text in the green background below. The whole thing is necessary?

**Comment by zhangzhongnan928** [comment]
> is there anything I can remove from the new logo? We have 2 logos + text in the green background below. The whole thing is necessary?

Don’t have to use that two logo. But if we need a logo, we can either use Shankai or Shankai +EURO2020.  Cannot use euro2020 along.
