### ISSUE TITLE
Shankai Tokens issuer should be Shankai instead of us.

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/TokenScript#316]
![AB292419-C12A-4028-A05C-CE3D1CE9FEB8](https://user-images.githubusercontent.com/33795543/71966552-edb6a380-3255-11ea-83ef-c3886717b04a.jpeg)

**Comment by James-Sangalli** [comment]
https://github.com/AlphaWallet/TokenScript/commit/dd312c17bbf1ca6469c01162fb64c7277d6a47a3

https://github.com/AlphaWallet/TokenScript-Repo/commit/8690be26e49d5c0cf5305927c75508383664a9d7
