### ISSUE TITLE
Redesign Karma Car Ownership Token

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/TokenScript#317]
![IMG_0130 2](https://user-images.githubusercontent.com/33795543/72036472-0fb03480-32ef-11ea-9cba-fd3406236525.PNG)

- [ ] Need to move the TS into the example folder @JamesSmartCell 
- [ ] we cover the Rinkeby gas for MagicLink free transfer @James-Sangalli 
- [ ] Need a better layout for the Karma Car Ownership Token @tomekalphawallet 
then,
- [ ] Need to implement the new TS design @tomekalphawallet  
- [ ] article from @JamesSmartCell

**Comment by tomekalphawallet** [comment]
![Screenshot 2020-01-27 17 35 08](https://user-images.githubusercontent.com/51817359/73193776-64471280-412b-11ea-98d2-7e995b1ff1df.png)

SVG Background:
https://www.dropbox.com/s/ytasncs2ycnrvax/karma_car_token.svg?dl=0

SVG Icon:
https://www.dropbox.com/s/v4dqgqa1mlxay26/Karma.svg?dl=0

Zeplin:
https://zpl.io/291wBZB

Sketch Cloud:
https://sketch.cloud/s/e4OJW/a/dno8kL

**Comment by zhangzhongnan928** [comment]
Don't need date and time.
it should have all the parts in below,
![car-token (7)](https://user-images.githubusercontent.com/33795543/74620452-56663980-518d-11ea-9e38-eadc21ef1c02.jpeg)

![IMG_1934](https://user-images.githubusercontent.com/33795543/74620537-a1804c80-518d-11ea-8d7c-7607bd6dee1f.PNG)
![IMG_1935](https://user-images.githubusercontent.com/33795543/74620544-a7762d80-518d-11ea-8cf6-7055e65caff8.PNG)
![IMG_1936](https://user-images.githubusercontent.com/33795543/74620547-a80ec400-518d-11ea-8fb4-986f669d3bda.PNG)
![IMG_1937](https://user-images.githubusercontent.com/33795543/74620548-a93ff100-518d-11ea-9889-6e04d71758d2.PNG)
![IMG_1938](https://user-images.githubusercontent.com/33795543/74620549-a9d88780-518d-11ea-9862-c3e8c281d43e.PNG)

**Comment by James-Sangalli** [comment]
@zhangzhongnan928 @JamesSmartCell still don't have the karma files...

**Comment by tomekalphawallet** [comment]
> @zhangzhongnan928 @JamesSmartCell still don't have the karma files...

Working on it.

**Comment by tomekalphawallet** [comment]
@zhangzhongnan928 @James-Sangalli 
Need more screenshots (I don't have Karma Car token):

- Start
- Sell
- Transfer

Already have:
- Market
- Attestations

What is the screenshot with "Challenge: No device found"?

**Comment by zhangzhongnan928** [comment]
> @zhangzhongnan928 @James-Sangalli
> Need more screenshots (I don't have Karma Car token):
> 
> * Start
> * Sell
> * Transfer
> 
> Already have:
> 
> * Market
> * Attestations
> 
> What is the screenshot with "Challenge: No device found"?

Start
This action is receiving a challenge from the IoT server on the car, and ask user to sign the challenge. If pass, the user will be granted access to the car.

![IMG_2105](https://user-images.githubusercontent.com/33795543/75857283-0a341e00-5e4a-11ea-9f76-04c9936d0afb.PNG)

![image](https://user-images.githubusercontent.com/33795543/75857642-a2ca9e00-5e4a-11ea-920c-2a417fd40fc7.png)


Sell and transfer are just standard TokenScript NFT screen like FIFA.

**Comment by tomekalphawallet** [comment]
Karma Token

![Karma](https://user-images.githubusercontent.com/51817359/75878194-82ceb680-5e19-11ea-9bc3-16d0caf1b8a9.png)

Additional Menu

![Karma_Menu](https://user-images.githubusercontent.com/51817359/75878218-895d2e00-5e19-11ea-8cba-299149ee2143.png)

Market

![Karma_Market](https://user-images.githubusercontent.com/51817359/75878134-6b8fc900-5e19-11ea-9e57-45790aabaeba.png)

Attestations

![Karma_Attestations](https://user-images.githubusercontent.com/51817359/75878154-73e80400-5e19-11ea-8839-bb97c158aa7a.png)

Challenge - I need a better copy.

![Karma_Challenge](https://user-images.githubusercontent.com/51817359/75878264-a2fe7580-5e19-11ea-942d-6fbdebbd4779.png)

Zeplin:
https://app.zeplin.io/project/5d0356be2f25b319dcc5944b/dashboard?seid=5e5f99b73b032a134317c8c7

**Comment by zhangzhongnan928** [comment]
Please add Make and VIN in token view


![75878194-82ceb680-5e19-11ea-9bc3-16d0caf1b8a9](https://user-images.githubusercontent.com/33795543/75878964-96583c80-5e6e-11ea-82bc-e56eb996e823.png)

**Comment by tomekalphawallet** [comment]
ok

**Comment by tomekalphawallet** [comment]
Committed few more tokens. 

![Karma_Menu](https://user-images.githubusercontent.com/51817359/75895696-48bfdd80-5e36-11ea-9419-02dab7790d77.png)

![Karma](https://user-images.githubusercontent.com/51817359/75895704-49f10a80-5e36-11ea-8697-c38f30dca4c0.png)

---

![Diablo](https://user-images.githubusercontent.com/51817359/75895674-42c9fc80-5e36-11ea-831c-ea132c55dba0.png)

---

![Herbi](https://user-images.githubusercontent.com/51817359/75895686-45c4ed00-5e36-11ea-9e3c-a3f6f23cc907.png)

**Comment by zhangzhongnan928** [comment]
@tomekalphawallet can we use real car pictures instead of cartoon ones? 
as cartoon makes it feels not real, not good for demo.

something like below
![Screen Shot 2020-03-16 at 12 40 14 pm](https://user-images.githubusercontent.com/33795543/76716169-691b6080-6783-11ea-9d25-16a53a8189f8.png)

**Comment by tomekalphawallet** [comment]
We can, but the real picture is usually not a vector. So it will not be saved as a scalable vector graphics (svg).

**Comment by tomekalphawallet** [comment]
https://adobe.ly/3aVSnDF

Any of these?

**Comment by zhangzhongnan928** [comment]
> https://adobe.ly/3aVSnDF
> 
> Any of these?

Better with a real Karma Car
https://www.google.com/search?q=karma+car&rlz=1C5CHFA_enSG814SG814&sxsrf=ALeKk03Fo7xqYkjwlAAuwRHlQo8V3L929Q:1584340855411&source=lnms&tbm=isch&sa=X&ved=2ahUKEwie447PsZ7oAhX38XMBHTKRDzAQ_AUoAXoECBUQAw

**Comment by tomekalphawallet** [comment]
Ok, my bad. I thought that this is a token to control James Brown's toy car that I saw in the office. So this is why I made it look like a toy. 

Updated look. 

SVG Background (iOS) - 
https://www.dropbox.com/s/cgz77y1xktqcnas/karma_background_ios.svg?dl=0

SVG Background (Android):
https://www.dropbox.com/s/yp499t8i61e9v6e/karma_bg_android.svg?dl=0

SVG Icon:
https://www.dropbox.com/s/wxxkl8gta0opmxk/karma_icon.svg?dl=0

Zeplin (iOS):
https://zpl.io/brQm9jD

Zeplin (Android):
https://zpl.io/aRdonde

Holden Year: 2019
Colour: Red
VIN: KL3TA4342DFFC21C2CC

Font:
SourceSans Pro Light Line: 14pt $323232

----

Preview:

<img width="1082" alt="Screenshot 2020-03-16 10 37 43" src="https://user-images.githubusercontent.com/51817359/76743004-3e74dc00-6772-11ea-9589-8267481b467f.png">

**Comment by James-Sangalli** [comment]
Moved the rest of the work assignment here: https://github.com/AlphaWallet/TokenScript-Examples/issues/32
