### ISSUE TITLE
UEFA Displays wrong on magic links 

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/TokenScript#319]
<img width="433" alt="Screenshot 2020-01-13 22 54 47" src="https://user-images.githubusercontent.com/16630514/72254325-c9910300-3657-11ea-8d12-3be1d4ac3ae9.png">

- Length is maladjusted

**Comment by hboon** [comment]
@James-Sangalli BTW if it is related to the spurious character between the 2 As, I have been meaning to file an issue on that, but keep forgetting. It’s also there on iOS but it’s not displayed. But you can see it if you inspect the JavaScript injected. Not sure what’s the cause.

**Comment by James-Sangalli** [comment]
@hboon this issue is regarding the incorrect size

**Comment by James-Sangalli** [comment]
CSS issues but no longer relevant as we have switched to starwars. UEFA can be mended another time if it is ever used...
