### ISSUE TITLE
Starwar

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/TokenScript#322]
![E0A90591-2B57-4735-9B1D-5F4244A4F8F1](https://user-images.githubusercontent.com/33795543/72606704-2ef43500-3973-11ea-80da-a21d86f336ca.jpeg)
Issuer: AlphaWallet or United Egalitarian Federation Association
Event name: Force 202 ABY Championship

**Comment by James-Sangalli** [comment]
https://github.com/AlphaWallet/TokenScript/commit/6eb88731185feace27d5846d8039527f83c85059
