### ISSUE TITLE
A 8 pages brochure to show case how tokenization "help" with car use case   

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/TokenScript#37]
Can be used stand-alone or in the deck.

A token can be blockchain token to non-blockchain token

Take out my mobile, and tell Siri I want to buy a new car for running “uber”, based on the tokens in my wallet, Siri knows the full picture on me like age, family, income, asset, preferred colour, lifestyle and etc. Siri suggest a Honda Odessey to me, with a customised loan option. Siri scared all the new car token on market, pick the one fit me best. Then compared with all the loan options. (As they are all tokenised, in a frictionless market, anyone can access all the information in the market). I click on button, with one atomic transection, the loan contract verified my tokens which proved my ability to pay, collect my first instalment Dai, speak to the car sell contract, transfer the full amount to car sell contract, car sell contract speak to Gov reg contract, Reg contract verify my indemnity tokens then issue reg token to me, car sell contract returns delivery token, receipt token and car token, car sell contract speak to manufacture contract, manufacture contract returns with warranty token. So after this one click I transfer out 10000 Dai, and receive a car token, a receipt token, a warranty token, a delivery token, a reg token, a loan token.

My asset 
My debit 

Told Siri, I want my car be delivery to my home on 18:00pm Tuesday. Siri add these requirement to delivery token, offers start being sent to delivery token, pickup the best offer based on reputation and cost. Then update the delivery token again with delivery company’s info. The delivery company go to warehouse pickup the car smoothly as their info already in delivery token. Company delivery the car to my home, he scanned my delivery token and received payment from car sell contract. I check the car, all good. Using my car token to use the car. Ask Siri to get me a permission of run “uber” services from Gov, Siri paid 10dai fee to GOV contract on the same time submitted tokens to the contract to verify that I am a qualified drivers. Get the permission token associate with my car token. Now Ih ave one more button on the car token which is start “Uber”, once I click start I start receive p2p offers and marketplace engine offers, my SIRI is picking up offers form me automatically. I start doing uber business. 

I’m leaving town for a while, with one click I start receiving	rent offers from p2P or marketplace offers. SIRI picks up the right ones to maximum my returns.

Car services
Car repaire
Car Collateralise
Car parking fee
Car used by my friend and family 
Car resell (with loan)
Etc.

**Comment by colourful-land** [comment]
Please post the idea to https://www.tokenscript.org/c/usecase and I'll follow up from there.
