### ISSUE TITLE
possible to allow random order for most elements in `<token>` and `<card>`?

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/TokenScript#379]
For `<token>` it has 

- asnx:module
- label
- some attributes, selections, etc
- `<cards>`

Is it possible to require that only the first 2 elements to be at the beginning of the TS file, while the rest of the elements can appear in any order following?

Similarly, every element inside `<card>`, except `<label>`, can be in any order. is it achievable with schema?

**Comment by darakhbharat** [comment]
I have investigated this completely and it is almost impossible to implement combination of sequence and random order as mentioned above.

It is still possible if all the random order elements either have 
- minOccurs="0" and maxOccurs="unbounded" OR
- minOccurs="0" and maxOccurs="1"

But this is not the case for TokenScript XSD. We have some of the elements as  maxOccurs="1" and some of them have maxOccurs="unbounded".

i.e. 

1. Under <token> we have below elements as maxOccurs="1" and rest of them are unbounded.
```
<element name="origins" minOccurs="0">
	<complexType>
		<sequence>
			<element ref="ts:ethereum"/>
		</sequence>
	</complexType>
</element>
<element ref="ts:cards"/>
<element minOccurs="0" ref="ts:grouping"/>
<element minOccurs="0" ref="ts:ordering"/>
```

2. Under <card> we have below elements as maxOccurs="1" and rest of them are unbounded.

```
<element minOccurs="0" ref="ts:origins"/>
<element minOccurs="0" name="input" type="ts:tokens"/>
<element minOccurs="0" name="output" type="ts:tokens"/>
<element minOccurs="0" ref="ts:transaction"/>
```


So the approach like where ever possible make it random order and whereever not make it strict sequence will be confusing while writing the XML.

**Comment by colourful-land** [comment]
Thanks.
