### ISSUE TITLE
Indicate blockchain name or subnet/mainnet for Activities tab?

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/TokenScript#390]
The Transactions tab used to show the blockchain's name but the Activity tab doesn't for the standard ERC20 and ERC721 activities. Should we have some kind of indication so we at least know which is mainnet/testnets?

Transactions (before)|Activity
-|-
<img width=200 src="https://user-images.githubusercontent.com/56189/94517000-a5169e80-0259-11eb-8396-086dd34418fe.png">| <img width=200 src="https://user-images.githubusercontent.com/56189/94516990-a1831780-0259-11eb-9f42-7ee513df94d4.png">

**Comment by colourfreak** [comment]
We don't have much real estate in Activities. If this is not super important, I would just keep in for open activities (do not touch the main activity view).

**In general:**
- If this is Mainnet = don't say anything, as this is default
- If this is Testnet = we can say if this is Ropsten, etc.

But don't say anything about Mainnet as it makes it cluttered. 

<img width="518" alt="Screenshot 2020-09-29 at 08 32 00" src="https://user-images.githubusercontent.com/51817359/94521593-9cf53980-022e-11eb-92d2-2505c0e1d2d4.png">

**Comment by hboon** [comment]
Sorry, just thought of 1 point: since TokenScript authors can define their own activity card, showing the blockchain name or an indicator might be inconsistent and misleading, so maybe we can't show it at all, or we'll have to somehow enforce it for custom cards too?

What if we show a little triangle at 1 of the corners with the the blockchain's fill color (for all or just testnets)? Then it's easier to enforce for custom activity views.

I don't have an opinion on this, so happy to leave it untouched so long as it's a conscious decision (for now at least).

**Comment by colourfreak** [comment]
I would not show it at all. Or if you really want to, add this triangle. However, he needs discoverability = on tap reveal more info what is this triangle for. 

<img width="459" alt="Screenshot 2020-09-29 at 09 10 07" src="https://user-images.githubusercontent.com/51817359/94524973-a3d27b00-0233-11eb-98a3-2bac11d53dff.png">

**Comment by hboon** [comment]
Nah, I don't mind. At least it's captured and thought through already. Closing. Feel free to re-open :)
