### ISSUE TITLE
Create a "scan QR code to buy a book" scenario

### ISSUE THREAD

**Issue by James-Sangalli** [AlphaWallet/TokenScript#40]
We need 2 graphs

First, a photo was taken from near the checkout counter or gate in 7-11. In the photo, the best seller books being sold in 7-11 (or any store) is not a real book, but cardboard that represents the book, with a QR code on it. The idea is the user can scan the QR code and buy the e-book from their mobile wallet. If the concept isn't apparent, consider, in the photo, have someone (or someone's hand) attempting to scan it.

Second, a mock-up of the screen of the user's mobile when she scanned the QR code. It should render a web page about the book (title, pictures, reviews, price) with a floating Tokenscript transaction where the user can clearly see that by paying $10USD, he will get a book token.

**Comment by colourful-land** [comment]
I renamed "Create an infographic to introduce TBML/TokenScript" because it sounds like a project. An issue is a task. I took the first task in this project as the title of this issue.
