### ISSUE TITLE
Tokenscript.org website allows user to upload a pdf file in a post but doesn't allow download the same file

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/TokenScript#53]
Reproduce.

1. Edit a post, upload a pdf file.

2. Save the post. Try to download the same file.

You get an error of some sort.

If you can't fix it, first immediately prevent the user being able to upload PDF, then fix it at your leisure.

**Comment by zhangzhongnan928** [comment]
ok

		
Victor Zhang
CEO, AlphaWallet
							
Not only display information, @Alpha_Wallet let you preform the functions: DEPOSIT, WITHDRAW, PAYBACK, GENERATE, MO… https://t.co/6dJfdvnM3i

**Comment by colourful-land** [comment]
The issue is kept open because we need PDF to be downloadable by the public, without registration. Let me know if discourse's pricing model is in conflict with this.

**Comment by colourful-land** [comment]
@bootingman The issue is kept open because we need PDF to be downloadable by the public, without registration. Let me know if discourse's pricing model is in conflict with this.

**Comment by colourful-land** [comment]
Close due to non-attentiveness. If you desire user to download without registration, post to somewhere else (e.g. github issue) and link to your post.
