### ISSUE TITLE
Draft an EIP for TokenScript (this will be a long process, but it will get people involved)

### ISSUE THREAD

**Issue by zhangzhongnan928** [AlphaWallet/TokenScript#55]
Draft an EIP for TokenScript (this will be a long process, but it will get people involved)

**Comment by colourful-land** [comment]
Again this is probably not executable because it is a project, not a task.  as you said:
> will be a long process

But I'll keep this one open as the first task of the project.

**Comment by zhangzhongnan928** [comment]
Done
Regards,
[image: AlphaWallet] <https://awallet.io/>

*Victor Zhang*

[image: AlphaWallet Github] <https://github.com/alpha-wallet> [image:
AlphaWallet Twitter] <https://twitter.com/Alpha_wallet> [image: AlphaWallet
Reddit] <https://www.reddit.com/r/AlphaWallet> [image: AlphaWallet Facebook]
<https://www.facebook.com/AlphaWallet/> [image: AlphaWallet Youtube]
<https://www.youtube.com/channel/UCPP12PQeQmQ4_6qXzNvZw-w/> [image:
AlphaWallet Linkedin] <https://www.linkedin.com/company/%CE%B1wallet/> [image:
AlphaWallet Weibo] <https://weibo.com/AlphaWallet>
Join our Telegram group. <https://t.me/AlphaWalletGroup>
