### ISSUE TITLE
community.alphawallet.com should be replaced by https://www.tokenscript.org/c/AlphaWallet

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/TokenScript#57]
Maybe we can simply give up community.alphawallet.com and instead update the app and the website to redirect people to https://www.tokenscript.org/c/AlphaWallet

1. Find all occurrences of links to community.alphawallet.com and replace those links to https://www.tokenscript.org/c/AlphaWallet

2. Add https://www.tokenscript.org/c/AlphaWallet to "Join the Community" section.

**Comment by colourful-land** [comment]
@hboon is there a reference to community.alphawallet.com in iOS app?

**Comment by hboon** [comment]
@colourful-land yes there is. But it's hard to get there. The user will be prompted to share it after using the app for a while. So we can update the URL.

**Comment by bootingman** [comment]
I had replaced these:
1. Footer of website homepage (all pages)
2. wiki.alphawallet.com
3. will try to update some articles which mentioned the url community.alphawallet.com (not all can be modified)

Add a cname record community.alphawallet.com points to www.tokenscript.org
