### ISSUE TITLE
Make all http://tokenscript.org and https://tokenscript.org/* be redirected to https

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/TokenScript#59]
Visit http://tokenscript.org and Chrome shows a "Not Secure" label in the URL bar. Safari shows something similar when you try to login or sign up.

<img width="683" alt="Screen Shot 2019-03-18 at 10 06 39 AM" src="https://user-images.githubusercontent.com/56189/54499422-a3320680-4965-11e9-9dc3-da8c49c19646.png">

**Comment by colourful-land** [comment]
DNS updated and this behaves normally to me now.

**Comment by zhangzhongnan928** [comment]
https://tokenscript.org/ is not working

**Comment by colourful-land** [comment]
So how did you get to https:∕∕tokenscript.org in the first place? 

- If you attempt to access http:∕∕tokenscript.org, you will be lead to https:∕∕www.tokenscript.org, not https:∕∕tokenscript.org

- if you attempt to access http:∕∕www.tokenscript.org, you will be lead to https:∕∕www.tokenscript.org, not https:∕∕tokenscript.org

Either way, there is no way you land in https:∕∕tokenscript.org. I never landed in that URL myself.

**Comment by zhangzhongnan928** [comment]
TokenScript.com
Click

**Comment by hboon** [comment]
Telegram on iOS does it (assumes https://) if you type just the domain name without the scheme. Tried on Notes.app which doesn’t do it, so it’s not iOS-wide.

**Comment by James-Sangalli** [comment]
@zhangzhongnan928 is this solved on your end now?

**Comment by zhangzhongnan928** [comment]
Yes
