### ISSUE TITLE
TokenScript.org cannot login with github

### ISSUE THREAD

**Issue by bobjiang** [AlphaWallet/TokenScript#60]
visiting tokenscrip.org, and try to login with github, cannot prompt github auth page, instead of following failure page.

<img width="800" alt="WechatIMG1312" src="https://user-images.githubusercontent.com/1224604/54514780-050a6480-4996-11e9-94b0-c75635b5141b.png">

**Comment by colourful-land** [comment]
@bootingman 1) solve it kindly; 2) if not solvable in a short time, simply disable sign-in with github until it is solved. Thanks!

**Comment by bootingman** [comment]
Seems it's not a bug, you have not allowed the quest from GitHub, please approve the request from GitHub, then you can log in with GitHub account.

I tried more than 5 times in different browsers, Firefox/Chrome/Brave/Vivaldi on PC/Mobile, 100% works.

**Comment by bobjiang** [comment]
It works for Safari on Mac (can register and login), 
but doesn't work for Chrome.

Chrome Version 72.0.3626.121 (Official Build) (64-bit)
Mac Darwin MacBook-Pro.local 18.2.0 Darwin Kernel Version 18.2.0

**Comment by colourful-land** [comment]
@theBergmann can you tell if it works for you?

**Comment by lanlan3322** [comment]
It is working on my chrome Version 73.0.3683.86 (Official Build) (64-bit). Login - Github - Create new account - Done.

**Comment by colourful-land** [comment]
Consider it solved per @theBergmann comment.
