### ISSUE TITLE
Screenshot illustration should have the same font size as text

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/TokenScript#66]
In computer literacy publication we have a common best practise that the emphasized text in a screenshot should be of the same visual size as the normal text of the publication.

Problem:

1. Download the PDF from https://github.com/AlphaWallet/TokenScript/releases/tag/0.3
2. Turn to page 23. Observe that the text size of emphasized text, like "Your Order Has Been Placed" or "Total Amount' is a lot smaller than the font of the paper.

I suggest making the screenshot 𝑏𝑒𝑓𝑜𝑟𝑒 and 𝑎𝑓𝑡𝑒𝑟 (❶ and ❷) vertical, that is, not side by side.

This way, the image will be auto-sized to fit the page, giving a much bigger font to match that of the paper text.

Also please strip off the white space around the screenshots so the actual screenshots will be auto-sized bigger.

**Comment by farrahfazirah** [comment]
Amended.

Purchase with shipment token

![purchase-with-shipment-token](https://user-images.githubusercontent.com/20555752/54806645-9854da00-4cb5-11e9-8bea-9433d9ef2f3e.JPEG)

Purchase without shipment token

![purchase-without-shipment-token](https://user-images.githubusercontent.com/20555752/54806701-c803e200-4cb5-11e9-81a6-17b5fd70bda4.JPEG)
