### ISSUE TITLE
Provide diagram for the casebook nozama

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/TokenScript#68]
@hboon 's diagram: https://www.tokenscript.org/t/i-sketched-a-diagram-to-help-me-understand-the-book-token-casebook/176

Can you produce a diagram following Boon's drawing>

Please communicate with me or Boon first with questions, since there are a few places the diagrams could be misread. You can do so by replying on that forum link.

If no question, I'll phone you to explain it before the work on the diagram.

**Comment by farrahfazirah** [comment]
I've recreated the architectural diagram with Boon's help

![nozamadiagram](https://user-images.githubusercontent.com/20555752/55521167-29fb1900-56b2-11e9-8175-98d1464cfcdb.png)

**Comment by colourful-land** [comment]
Your SVG doesn't work on either Firefox or Chrome. See the screenshot. Can you check if you can export one that I can use on the web? Maybe tweak the options a bit?

![snapshot](https://user-images.githubusercontent.com/548435/55558986-f57e7000-5738-11e9-8617-4d55dd868012.gif)

**Comment by colourful-land** [comment]
[nozamadiagram.svg.gz](https://github.com/AlphaWallet/TokenScript/files/3043627/nozamadiagram.svg.gz)

When you make SVG, you can upload to github by converting it to gz.

    $ gzip nozamadiagram.svg

**Comment by farrahfazirah** [comment]
[nozamadiagram.svg.gz](https://github.com/AlphaWallet/TokenScript/files/3046736/nozamadiagram.svg.gz)

**Comment by colourful-land** [comment]
Thanks the new file worked.
