### ISSUE TITLE
use shtml for <view-iconified>?

### ISSUE THREAD

**Issue by colourful-land** [AlphaWallet/TokenScript#74]
`<ts:view>` allows a direct `<html>`.  That's all fine because we can reference the entire content of a `<ts:view>` from a standalone HTML page.

I am inclined to make `<ts:view-iconified>` differently - make a type for it called `shtml`. If you played with web development between end of 90s and beginning of 2000s, you know `shtml` is just a segment of html without the leading `<html><head>...</head><body>` and the trailing `</body></html>` and is intended to be inserted in a full-formed HTML page.

There are a few reasons for doing so.

1. `<ts:view-iconfiied>` is useful in rendering tokens in a different context than mobile wallet. For one example, in the shopping cart on the dapp, as in this image, observe 'warranty token' before it is purchased:
https://raw.githubusercontent.com/AlphaWallet/TokenScript/master/doc/img/purchase-with-shipment-token.JPEG
So it is conceptually suitable to be a segment of html.

2. I envision some tokens to have 20 to 50 cards (not all will be shown below a token - many cards are context-based, like `balance-card` which only shows when the user checks out). By the time we reach there, the css file shared between these cards might be 1000KB. This might still be okay if you render a card, but to load such css file 10 times for a view that has 10 tokenInstance is daunting. If we enforce shtml in `<ts:view-iconified>` developers will be limited to inline styling.

**Comment by hboon** [comment]
I think they should all be without the html, head and body envelopes so the TokenScript client can set the appropriate viewport, script tags, standard style classes for them easily. Implementation-wise, the prototype iOS version has TokenScript files that only includes the body tag (but we can change that of course). Is there a reason for them to include those envelope tags for <ts:view>?

Also keep https://reactjs.org/docs/introducing-jsx.html in mind. I think JSX might be worth supporting in the future, even if we don’t directly enforce React especially for <view-iconified>, but not sure how it can be consistent with other view types.

**Comment by colourful-land** [comment]
> Is there a reason for them to include those envelope tags for ts:view?

Just stylesheets. The stylesheets are linked only in `<head>`. The alternative method is do the link outside the view (but inside the action> and inject them by the wallet:

    <ts:token-card>
        <style type="text/css">&styles;</style>
        <ts:view>&token.en;</ts:view>
    </ts:token-card>

where `&token.en;` is a reference to `token.en.shtml` and '&style;'.

From your reply, it seems this alternative is cleaner?

**Comment by hboon** [comment]
> Just stylesheets. The stylesheets are linked only in `<head>`. The alternative method is do the link outside the view (but inside the action> and inject them by the wallet:

So both `<ts:token-card>` and `<ts:action>` will have `<style>` as their direct child?

Yes, this seems cleaner. And also makes it easier for the developer to share styles across the views.

Downside is we will be trading off developer experience because they can't render the token.en.shtml static file directly in a browser during development to layout and style the contents of `<ts:view>`.

I think it's worth it and in the web community, it's pretty normal to have a pipeline to generate the final assets even for dev/live-reload anyway, so we can provide a tool or library to combine them together into a single file during development, if necessary, later.

**Comment by colourful-land** [comment]
Done following @hboon 's advice

**Comment by James-Sangalli** [comment]
@hboon are you sure using shtml is a good idea? this makes it very hard to test what the layout will look like as you cannot see the styling... 

I am using this right now and it is a pain.

**Comment by hboon** [comment]
> I am using this right now and it is a pain.

@James-Sangalli Are you referring to building https://github.com/AlphaWallet/TokenScript/pull/126?

A simple way to do this manually now is to just create the HTML for debugging and then cut out the relevant sections like the view and styles once you are done.

Form the file like this:

```
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1,  maximum-scale=1, shrink-to-fit=no">
</head>
<style type="text/css">
&style;
</style>
&dai.en;
</html>
```

I'm abusing the "entity reference syntax" here for illustration here. Replace &style; and &dai.en; with the contents of their respective files. When you are done, copy them out into their respective files again.

You'll usually also need to include the standard styles in the `<head>`, but we don't use it in the dai TokenScript, so they aren't necessary.

This is basically what TokenScript client does to render the HTML views, minus the token data and data updates. When we get to building tools, we could have a cli tool/subcommand that generates the HTML file above by watching for changes in the TokenScript source files (.xml, .shtml, .css), possibly even inserting a script into the resulting HTML so we can trigger the desktop browser to reload without an explicit refresh. So you can do:

1. Run cli on the .xml TokenScript file
2. cli generates the HTML file
3. cli informs browser to open the generated HTML file
4. Edit dai.en.shtml or .css
5. cli regenerates HTML and informs browser to refresh

Developer repeats step (4). If we don't automate step (5), then the developer just has to manually refresh in the browser after each edit.

**Comment by colourful-land** [comment]
The idea of using CDATA instead of xhtml for shtml files was brought up so that developers don't have to do well-formed html was brought up recently. The issues with that approach are:

you can't use entity references in CDATA, which means you can't do this:

    <!<[CDATA &token.en; >>

The alternative, which is to add CDATA header in the beginning of shtml files, is worse.

The second reason of not doing so is that we can enforce reference of attributes in the shtml by the way it is typed in the main xml file. If you use CDATA, schema will not be able to enforce it.
