### ISSUE TITLE
To support URL Pattern Whitelisting in coming build or not?

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/TokenScript#85]
Are we supporting whitelisting URLs? The iOS TokenScript client supports whitelisting, so it blocks everything by default. But we don’t have a way to support the whitelisting of URL patterns in the TokenScript file yet.

Will the workshop let developers write their TokenScript to connect to any URL?

cc @JamesSmartCell

**Comment by colourful-land** [comment]
Practically without xml signature validation, the whitelist doesn't make it more secure. Also our hands are pretty full, it would be lovely to see the capacity to call smart contract calls from TBML (think dai or xdai bridge) than having security sorted out for demonstration.

**Comment by hboon** [comment]
Agreed. Have excluded whitelisting in the branch for TestFlight-ing.
