### ISSUE TITLE
make error on master commit: c152cd897702f7e1b913aa53aa13b24d2756970c

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/TokenScript#88]
I would fish myself, but we are rushing and it seems not immediately alarming.

```
$ make
# XML Canonicalization
xmlstarlet c14n AdmissionTicket.xml  > AdmissionTicket.tsml.xml
cards/token.en.shtml:32.16: Entity 'nbsp' not defined
         &nbsp;
               ^
cards/token.en.shtml:56.1: chunk is not well balanced

^
AdmissionTicket.xml:35.19: Failure to process entity token.en
        &token.en;
                  ^
AdmissionTicket.xml:35.19: Entity 'token.en' not defined
        &token.en;
                  ^
Error: unable to parse file "AdmissionTicket.xml"
make: *** [AdmissionTicket.tsml] Error 3
```

Using CDATA fixes the entity warnings. Which we then get:

```
$ make
# XML Canonicalization
xmlstarlet c14n AdmissionTicket.xml  > AdmissionTicket.tsml.xml
# Validating -- might take a long time to download xsd files from w3.org                                                                     
xmllint --noout --schema ../../schema/tokenscript.xsd AdmissionTicket.tsml.xml                                                               

http://www.w3.org/TR/2008/REC-xmldsig-core-20080610/xmldsig-core-schema.xsd:1: parser error : Document is empty

^
../../schema/tokenscript.xsd:12: element import: Schemas parser error : Element '{http://www.w3.org/2001/XMLSchema}import': Failed to parse th
e XML resource 'http://www.w3.org/TR/2008/REC-xmldsig-core-20080610/xmldsig-core-schema.xsd'.
WXS schema ../../schema/tokenscript.xsd failed to compile
```

**Comment by colourful-land** [comment]
@hboon this happened.

1. You hit a problem not using CDATA.
2. You fixed it with CDATA, but as you re-run Makefile, you failed to download the XML signature XSD file from w3.org's website, which happens roughly 1 out of 5 times as the website throttles heavily.
3. You mistook that error as a problem introduced by CDATA (after all 𝑦𝑜𝑢 did 𝑛𝑜𝑡ℎ𝑖𝑛𝑔 𝑒𝑙𝑠𝑒). So you used entity reference instead. Then you hit a deadlock because there are too many entity references in the lower half of the script.

**Comment by colourful-land** [comment]
With the PR, the output is this:

    # XML Canonicalization
    xmlstarlet c14n AdmissionTicket.xml  > AdmissionTicket.tsml.xml
    # Validating -- might take a long time to download xsd files from w3.org
    # If you see an error 'http://www.3.org...: parser error : Document is empty' read the comments in 
    Makefile
    xmllint --noout --schema ../../schema/tokenscript.xsd AdmissionTicket.tsml.xml
    AdmissionTicket.tsml.xml validates
    mv AdmissionTicket.tsml.xml AdmissionTicket.tsml

**Comment by hboon** [comment]
Fixed.

**Comment by hboon** [comment]
I generated and tested against the canonicalized form, but haven't once gotten it to validate due to not being able to downloading the XSD even with different IP addresses.
