### ISSUE TITLE
Include the FIFA un-canonicalized TokenScript file and supporting files in this repo?

### ISSUE THREAD

**Issue by hboon** [AlphaWallet/TokenScript#98]
- [x] A yes or no from @colourful-land or if there's a better place to put it. 
- [ ] Rename title
- [ ] Someone do it

**Comment by colourful-land** [comment]
I agree that fifa is an example, but it's far more complicated than other examples and should not be mentioned in tutorial #103.

I fancy that it should be the last example in the order demonstrated by #110

**Comment by colourful-land** [comment]
the answer is no. @hboon I feel we should keep our work on fifa-ticket token in the `contracts` repo and submit the final result to https://github.com/AlphaWallet/TokenScript-Repo
